cookbook 'yumfastestmirror',  github: 'DQNEO/cookbook-yumfastestmirror'
cookbook 'git',               github: 'DQNEO/cookbook-git'
cookbook 'remi',              github: 'DQNEO/cookbook-remi'
cookbook 'emacs',             github: 'DQNEO/cookbook-emacs'
cookbook 'zsh',               github: 'DQNEO/cookbook-zsh'
cookbook 'berkshelf-minimum', github: 'DQNEO/cookbook-berkshelf-minimum'
cookbook 'httpd',             github: 'DQNEO/cookbook-httpd'
cookbook 'timezone',          github: 'DQNEO/cookbook-timezone'
